#!/bin/bash

set -e

source /opt/resource/common.sh

log "Checking version of Solace Product Download resource"

readPayload

current_checksum=$(cat $PAYLOAD | /usr/bin/jq '.source' | /usr/bin/sha256sum | awk '{ print $1 }')
last_checksum=$(getPayloadProperty ".version.config_checksum")

log "Last checksum $last_checksum, current checksum $current_checksum"

token=$(getPayloadProperty ".source.pivnet_token")
if [ ! -z "$token" ]; then
  last_version=$(jq -r '.version.pubsub_release_id // ""' < $PAYLOAD)
  getPubsubReleaseVersion

  log "Last pubsub version id $last_version, current pubsub version id $current_version"
fi

if [ "$current_checksum" == "$last_checksum" ] && [ -z $PUBSUB_PIVNET_VERSION_ID -o "$PUBSUB_PIVNET_VERSION_ID" == "$last_version" ]; then
  echo '[]'
else
  version=${PUBSUB_PIVNET_VERSION_ID:-""}
  echo "[{\"config_checksum\":\"$current_checksum\",\"pubsub_version_id\":\"$version\"}]"
fi

